### ISSUE TITLE
Adicionar compartilhamento pelo Whatsapp

### ISSUE THREAD

**Issue by nandomoreirame** [haskellcamargo/gemidao-do-zap-free#6]
Seria uma boa sair compartilhando nos grupo tudo!

**Comment by jaonoctus** [comment]
@haskellcamargo posso mandar mais um PR? :smile:

**Comment by nandomoreirame** [comment]
eu aprovo 🤘

**Comment by jaonoctus** [comment]
@nandomoreirame onde seria bom colocar o botão? Em baixo do "enviar"?
